name: build TD files

on:
  push:
    branches:
      - master

jobs:
  convert-via-pandoc:
    runs-on: ubuntu-latest
    container:

      image: docker://pandoc/latex:2.9
      options: --entrypoint=sh

    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: create output directories
        run: mkdir output

      - name: convert md to pdf
        run: |
          find ./ -iname '*.md' -type f -exec sh -c 'pandoc --filter pandoc-crossref -s -N ${0} -o output/$(basename $0 .md).pdf' {} \;
#
#      - name: LaTeX
#        uses: xu-cheng/latex-action@v2
#        with:
#          working_directory: output
#          root_file: "*.tex"
#          glob_root_file: true

      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: output/*.pdf

  publish:
    needs: convert-via-pandoc
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: artifacts
        uses: actions/download-artifact@v2
        with:
          name: files
          path: output

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: output
          target_folder: exercices

